name: Integration Tests Browser

on:
  workflow_dispatch:
  # Web devices are not supported for integration tests yet.
  #pull_request:
  #push:
  #  tags:
  #    - 'v*'

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@main
        with:
          flutter-version: '3.x'
          channel: 'stable'
      - uses: nanasess/setup-chromedriver@master
      - run: |
          export DISPLAY=:99
          chromedriver --port=4444 --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
      - run: flutter pub get
      - run: "cd example && flutter test -d chrome integration_test/app_test.dart"